[package]
name = "tgopher"
version = "0.1.1"
edition = "2021"
authors = ["hlts2"]

license = "MIT"
description = "Gopher passes through the terminal"
repository = "https://github.com/hlts2/tgopher"
readme = "README.md"
keywords = ["tgopher"]

[dependencies]
termion = "1.5.6"
