[package]
name = "tgopher"
version = "0.1.0"
edition = "2021"
authors = ["hlts2"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.6"
